version: '3.1'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: Guille
      POSTGRES_PASSWORD: 4Emperador
      POSTGRES_DB: transparent
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
